// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: mb8_smartwatch

#ifndef _MB8_SMARTWATCH_UI_H
#define _MB8_SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_877344450);    // assets/icons8-bed-75.png
LV_IMG_DECLARE(ui_img_1424755116);    // assets/icons8-heart-70.png
LV_IMG_DECLARE(ui_img_985356849);    // assets/icons8-bluetooth-off-24.png
LV_IMG_DECLARE(ui_img_106406083);    // assets/icons8-bluetooth-24.png
LV_IMG_DECLARE(ui_img_1149670027);    // assets/icons8-battery-30.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
