// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: mb8_smartwatch

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_BedPanel;
extern lv_obj_t * ui_BedIcon;
extern lv_obj_t * ui_BedData;
extern lv_obj_t * ui_HRPanel;
extern lv_obj_t * ui_HRIcon;
extern lv_obj_t * ui_HRData;
extern lv_obj_t * ui_TimeText;
extern lv_obj_t * ui_BluetoothStateDisconnected;
extern lv_obj_t * ui_BluetoothStateConnected;
extern lv_obj_t * ui_BatteryStatus;
extern lv_obj_t * ui_BatteryStatusData;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

