// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: mb8_smartwatch

#include "../ui.h"

lv_obj_t * ui_MainScreen;
lv_obj_t * ui_BedPanel;
lv_obj_t * ui_BedIcon;
lv_obj_t * ui_BedData;
lv_obj_t * ui_HRPanel;
lv_obj_t * ui_HRIcon;
lv_obj_t * ui_HRData;
lv_obj_t * ui_TimeText;
lv_obj_t * ui_BluetoothStateDisconnected;
lv_obj_t * ui_BluetoothStateConnected;
lv_obj_t * ui_BatteryStatus;
lv_obj_t * ui_BatteryStatusData;

// event funtions

// build funtions

void anim_start_event_cb(lv_event_t* e)
{
    lv_anim_t* a = lv_event_get_param(e);
    if (a) a->act_time = 120;
}


void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t* tileview = lv_tileview_create(ui_MainScreen);
    lv_obj_set_style_bg_color(tileview, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_scrollbar_mode(tileview, LV_SCROLLBAR_MODE_OFF);

    lv_obj_add_event_cb(tileview, anim_start_event_cb, LV_EVENT_SCROLL_BEGIN, NULL);

    lv_obj_t* tile1 = lv_tileview_add_tile(tileview, 0, 0, LV_DIR_RIGHT | LV_DIR_LEFT);
    lv_obj_t* tile2 = lv_tileview_add_tile(tileview, 1, 0, LV_DIR_LEFT | LV_DIR_RIGHT);

    lv_obj_t* label = lv_label_create(tile2);
    lv_label_set_text(label, "Scroll left");
    lv_obj_center(label);
    lv_obj_set_style_text_color(label, lv_color_hex(0xffffff), LV_PART_MAIN);

    ui_BedPanel = lv_obj_create(tile1);
    lv_obj_set_width(ui_BedPanel, 180);
    lv_obj_set_height(ui_BedPanel, 180);
    lv_obj_set_x(ui_BedPanel, 0);
    lv_obj_set_y(ui_BedPanel, -95);
    lv_obj_set_align(ui_BedPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BedPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BedPanel, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BedPanel, lv_color_hex(0x6E44FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BedPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BedPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedIcon = lv_img_create(ui_BedPanel);
    lv_img_set_src(ui_BedIcon, &ui_img_877344450);
    lv_obj_set_width(ui_BedIcon, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_BedIcon, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_BedIcon, -43);
    lv_obj_set_y(ui_BedIcon, -43);
    lv_obj_set_align(ui_BedIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BedIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BedIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BedData = lv_label_create(ui_BedPanel);
    lv_obj_set_width(ui_BedData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedData, -52);
    lv_obj_set_y(ui_BedData, 42);
    lv_obj_set_align(ui_BedData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedData, "--");
    lv_obj_set_style_text_color(ui_BedData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BedData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BedData, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HRPanel = lv_obj_create(tile1);
    lv_obj_set_width(ui_HRPanel, 180);
    lv_obj_set_height(ui_HRPanel, 180);
    lv_obj_set_x(ui_HRPanel, 0);
    lv_obj_set_y(ui_HRPanel, 95);
    lv_obj_set_align(ui_HRPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HRPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HRPanel, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HRPanel, lv_color_hex(0xFE0251), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HRPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HRPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HRPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HRIcon = lv_img_create(ui_HRPanel);
    lv_img_set_src(ui_HRIcon, &ui_img_1424755116);
    lv_obj_set_width(ui_HRIcon, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_HRIcon, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_HRIcon, -43);
    lv_obj_set_y(ui_HRIcon, -38);
    lv_obj_set_align(ui_HRIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HRIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HRIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HRData = lv_label_create(ui_HRPanel);
    lv_obj_set_width(ui_HRData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HRData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HRData, -52);
    lv_obj_set_y(ui_HRData, 42);
    lv_obj_set_align(ui_HRData, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HRData, "--");
    lv_obj_set_style_text_color(ui_HRData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HRData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HRData, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeText = lv_label_create(tile1);
    lv_obj_set_width(ui_TimeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeText, 0);
    lv_obj_set_y(ui_TimeText, -232);
    lv_obj_set_align(ui_TimeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeText, "15:20");
    lv_obj_set_style_text_color(ui_TimeText, lv_color_hex(0xD5D5D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BluetoothStateDisconnected = lv_img_create(tile1);
    lv_img_set_src(ui_BluetoothStateDisconnected, &ui_img_985356849);
    lv_obj_set_width(ui_BluetoothStateDisconnected, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BluetoothStateDisconnected, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_BluetoothStateDisconnected, -17);
    lv_obj_set_y(ui_BluetoothStateDisconnected, -204);
    lv_obj_set_align(ui_BluetoothStateDisconnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BluetoothStateDisconnected, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BluetoothStateDisconnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BluetoothStateConnected = lv_img_create(tile1);
    lv_img_set_src(ui_BluetoothStateConnected, &ui_img_106406083);
    lv_obj_set_width(ui_BluetoothStateConnected, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_BluetoothStateConnected, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_BluetoothStateConnected, -17);
    lv_obj_set_y(ui_BluetoothStateConnected, -204);
    lv_obj_set_align(ui_BluetoothStateConnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BluetoothStateConnected, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BluetoothStateConnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryStatus = lv_img_create(tile1);
    lv_img_set_src(ui_BatteryStatus, &ui_img_1149670027);
    lv_obj_set_width(ui_BatteryStatus, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_BatteryStatus, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_BatteryStatus, 11);
    lv_obj_set_y(ui_BatteryStatus, -203);
    lv_obj_set_align(ui_BatteryStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BatteryStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BatteryStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BatteryStatusData = lv_bar_create(ui_BatteryStatus);
    lv_bar_set_value(ui_BatteryStatusData, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryStatusData, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryStatusData, 20);
    lv_obj_set_height(ui_BatteryStatusData, 9);
    lv_obj_set_x(ui_BatteryStatusData, -1);
    lv_obj_set_y(ui_BatteryStatusData, -1);
    lv_obj_set_align(ui_BatteryStatusData, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryStatusData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryStatusData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryStatusData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryStatusData, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryStatusData, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryStatusData, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_tile(tileview, tile2, LV_ANIM_ON);
}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_BedPanel = NULL;
    ui_BedIcon = NULL;
    ui_BedData = NULL;
    ui_HRPanel = NULL;
    ui_HRIcon = NULL;
    ui_HRData = NULL;
    ui_TimeText = NULL;
    ui_BluetoothStateDisconnected = NULL;
    ui_BluetoothStateConnected = NULL;
    ui_BatteryStatus = NULL;
    ui_BatteryStatusData = NULL;

}
